create table USERS (
  ID serial,
  USER_NAME varchar(100) NOT NULL,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL
);

create table FAVORITES (
    ID serial,
    LOCATION_NAME VARCHAR(100) NOT NULL,
    BORO_NAME VARCHAR(100) NOT NULL,
    TYPE_NAME VARCHAR(100),
    PROVIDER VARCHAR(100),
    SSID VARCHAR(100),
    REMARKS VARCHAR(100),
    NOTES VARCHAR(100),
    USER_ID VARCHAR(100)
)